<?php

return array(
	'title'=>'Universal Order of the Morning Star',

	'en'=>'English',
	'it'=>'Italian',
	'sp'=>'Spanish',
	'sv'=>'Swedish',
	'lang-en'=>'Change language to English',
	'lang-sv'=>'Ändra språk till Svenska',

	'menu-home'=>'Home',
	'menu-lodges'=>'Lodges',
	'menu-membership'=>'Membership',
	'menu-library'=>'Library',
	'menu-forum'=>'Forum',
	'menu-contact'=>'Contact Us',
	'menu-about-us'=>'About Us',
	'menu-account'=>'Account',
	'menu-settings'=>'Settings',

	'header-user-signup'=>'Sign up',
	'header-user-login'=>'Log in',
	'header-user-logout'=>'Log out',

	'login-title'=>'Log in...',
	'login-user'=>'User name',
	'login-password'=>'Password',
	'login-ok-button'=>'Log in',

	'site-foot'=>'Universal Order of the Morning Star, All rights reserved, based in Wales, UK',
	'site-description'=>'Universal Order of the Morning Star derives its tradition from the Open Source Order of the Golden Dawn, and thus is part of the Open Source movement that promotes a free and open society, including spiritual and occult tradition.',
	'site-keywords'=>'Golden Dawn, Open Source, Magick, Ritual Magic, Magic, Ceremonial Magic, Thaumaturgi, Theurgy, Tarot, Astrology, Enochian Magic, Qabalah',
	'site-foot-left'=>'Universal Order of the Morning Star is a modern Golden Dawn-styled Hermetic and Esoteric Order that derives its tradition from the Order of Golden Dawn / Stella Matutina, but with new adaptations and innovations.',
	'site-foot-right'=>'All material on this web-site is licensed under the Creative Commons license and may so be used freely for uncommercial purpose.',

	'yes'=>'Yes',
	'no'=>'No',
	'ok'=>'OK',
	'cancel'=>'Cancel',
	'date'=>'Date',
	'member'=>'Member',
	'email'=>'Email',
	'user'=>'User',
	'username'=>'Username',
	'unknown'=>'Unknown',
	'password'=>'Password',
	'access'=>'Access',
	'status'=>'Status',
	'help'=>'Help',
	'edit'=>'Edit',
	'change'=>'Change',
	'save'=>'Save',
	'saveas'=>'Save as',
	'del'=>'Delete',
	'delcheck'=>'Delete Checked',
	'from'=>'From',
	'to'=>'To',
	'reply'=>'Reply',
	'send'=>'Send',
	'subject'=>'Subject',
	'message'=>'Message',
	'logout'=>'Logout',
	'login'=>'Login',
	'register'=>'Register',
	'has_written'=>'{user} has written',
	'prev'=>'Previous',
	'next'=>'Next',
	'quote'=>'Quote',
	'lang'=>'Language',
	'linkid'=>'Link Id',
	'url'=>'URL',
	'raccess'=>'Read Access',
	'waccess'=>'Write Access',
	'mail'=>'Mail',
	'log'=>'Log',
	'forum'=>'Forum',
	'rel'=>'Relation',
	'rels'=>'Relations',
	'note'=>'Note',
	'notes'=>'Journal',
	'gallery'=>'Gallery',
	'settings'=>'Settings',
	'administration'=>'Administration',
	'db_err_connect'=>'Error: Could not connect to database!',
	'db_err_query'=>'Error: The query failed!',
	'qb'=>'Quickbar',
	'qb_info'=>'Info about relation',
	'qb_log'=>'Log',
	'qb_mail'=>'Write Mail',
	'qb_note'=>'Journal',
	'qb_rel'=>'Relations',
	'qb_gallery'=>'Gallery',
	'bc_sep'=>' ›› ',
	'wiki-index'=>'Start_Page',

	'stat-mail'=>'You have {num} unread mail',
	'stat-mails'=>'You have {num} unread mails',
	'stat-log-post'=>'You have {num} unread post in your log',
	'stat-log-posts'=>'You have {num} unread posts in your log',
	'stat-forum-reply'=>'You have {num} unread reply in the forum',
	'stat-forum-replies'=>'You have {num} unread replies in the forum',
	'stat-numbers'=>array('no','one','two','three','four','five','six','seven','eight','nine','ten'),

	'numbers'=>array(
		'zero',
		'one',
		'two',
		'three',
		'four',
		'five',
		'six',
		'seven',
		'eight',
		'nine',
		'ten',
		'eleven',
		'twelve',
		'thirteen',
		'fourteen',
		'fifteen',
		'sixteen',
		'seventeen',
		'eighteen',
		'nineteen',
		'twenty',
	),

	'months'=>array(
		'',
		'January',
		'February',
		'March',
		'April',
		'May',
		'June',
		'July',
		'August',
		'September',
		'October',
		'November',
		'December',
	),

	'weekdays'=>array(
		'Monday',
		'Tuesday',
		'Wednesday',
		'Thursday',
		'Friday',
		'Saturday',
		'Sunday',
	),

	'format_date'=>array(
		':th ',
		':st ',
		':nd ',
		':rd ',
		'Yesterday',
		'Today',
		'{day}{mon}{yr}',
		'{day} at {hr}:{min}',
		'{day}{mon}{yr} at {hr}:{min}',
	),

	'format_time'=>array(
		' minutes',
		' hours',
		' days',
		' months',
		' years ',
	),

	'accesses'=>array(

		array(
			'visitor',
			'member',
			'crew',
			'admin',
			'master',
		),

		array(
			'Visitor',
			'Member',
			'Crew',
			'Admin',
			'Master',
		),
	),

	'statuses'=>array(
		1=>'Online',
		2=>'Confirmed',
		4=>'Accepted',
		8=>'Warned',
		16=>'Banned',
		32=>'Removed',
		64=>'Hidden',
		128=>'Guest',
	),

	'name_format'=>'{gender}&nbsp;{name}',
	'name_female'=>'Soror',
	'name_male'=>'Frater',
);
