<?php

return array(
	'title'=>'Universal Order of the Morning Star',

	'en'=>'Engelska',
	'it'=>'Italienska',
	'sp'=>'Spanska',
	'sv'=>'Svenska',
	'lang-en'=>'Change language to English',
	'lang-sv'=>'Ändra språk till Svenska',

	'menu-home'=>'Hem',
	'menu-lodges'=>'Loger',
	'menu-membership'=>'Medlemskap',
	'menu-library'=>'Bibliotek',
	'menu-forum'=>'Forum',
	'menu-contact'=>'Kontakt',
	'menu-about-us'=>'Om oss',
	'menu-account'=>'Konto',
	'menu-settings'=>'Inställningar',

	'header-user-signup'=>'Registrera',
	'header-user-login'=>'Logga in',
	'header-user-logout'=>'Logga ut',

	'login-title'=>'Logga in...',
	'login-user'=>'Användarnamn',
	'login-password'=>'Lösenord',
	'login-ok-button'=>'Logga in',

	'site-foot'=>'Universal Order of the Morning Star, Alla rättigheter förbehållna, baserad i Wales, UK',
	'site-description'=>'Universal Order of the Morning Star ärver sin tradition från Open Source Order of the Golden Dawn, och är därmed del av Open Source rörelsen som förespråkar ett fritt och öppet samhälle, inklusive spirituell och ockult tradition.',
	'site-keywords'=>'Golden Dawn, Open Source, Magick, Ritual Magic, Magic, Ceremonial Magic, Magi, Gyllene Gryningen, Thaumaturgi, Theurgy, Tarot, Astrology, Astrologi, Enochian Magic, Qabalah, Kabbala',
	'site-foot-left'=>'Universal Order of the Morning Star ärver sin tradition från Open Source Order of the Golden Dawn, och är därmed del av Open Source rörelsen som förespråkar ett fritt och öppet samhälle, inklusive spirituell och ockult tradition.',
	'site-foot-right'=>'Allt material på den här websidan är licensierat under Creative Commons licensen och kan därmed fritt användas för icke kommersiellt bruk.',

	'yes'=>'Ja',
	'no'=>'Nej',
	'ok'=>'OK',
	'cancel'=>'Avbryt',
	'date'=>'Datum',
	'member'=>'Medlem',
	'email'=>'E-Post',
	'user'=>'Användare',
	'username'=>'Användarnamn',
	'unknown'=>'Okänd',
	'password'=>'Lösenord',
	'access'=>'Behörighet',
	'status'=>'Status',
	'help'=>'Hjälp',
	'edit'=>'Redigera',
	'change'=>'Ändra',
	'save'=>'Spara',
	'saveas'=>'Spara som',
	'del'=>'Ta bort',
	'delcheck'=>'Ta bort markerade',
	'from'=>'Från',
	'to'=>'Till',
	'reply'=>'Svara',
	'send'=>'Skicka',
	'subject'=>'Ämne',
	'message'=>'Meddelande',
	'logout'=>'Logga ut',
	'login'=>'Logga in',
	'register'=>'Registrera',
	'has_written'=>'{user} har skrivit',
	'prev'=>'Föregående',
	'next'=>'Nästa',
	'quote'=>'Citera',
	'lang'=>'Språk',
	'linkid'=>'Länk Id',
	'url'=>'URL',
	'raccess'=>'Läsbehörighet',
	'waccess'=>'Skrivbehörighet',
	'mail'=>'Mail',
	'log'=>'Logg',
	'forum'=>'Forum',
	'rel'=>'Relation',
	'rels'=>'Relationer',
	'note'=>'Inlägg',
	'notes'=>'Journal',
	'gallery'=>'Galleri',
	'settings'=>'Inställningar',
	'administration'=>'Administration',
	'db_err_connect'=>'Fel: Kunde inte koppla upp mot databasen!',
	'db_err_query'=>'Fel: Förfrågan misslyckades!',
	'qb'=>'Snabbmeny',
	'qb_info'=>'Info om relationen',
	'qb_log'=>'Logg',
	'qb_mail'=>'Skriv Mail',
	'qb_note'=>'Dagbok',
	'qb_rel'=>'Relationer',
	'qb_gallery'=>'Galleri',
	'bc_sep'=>' ›› ',
	'wiki-index'=>'Startsida',

	'stat-mail'=>'Du har {num} oläst mail',
	'stat-mails'=>'Du har {num} olästa mail',
	'stat-log-post'=>'Du har {num} oläst inlägg i din logg',
	'stat-log-posts'=>'Du har {num} olästa inlägg i din logg',
	'stat-forum-reply'=>'Du har {num} oläst svar i forumet',
	'stat-forum-replies'=>'Du har {num} olästa svar i forumet',
	'stat-numbers'=>array('inga','ett','två','tre','fyra','fem','sex','sju','åtta','nio','tio'),

	'numbers'=>array(
		'noll',
		'ett',
		'två',
		'tre',
		'fyra',
		'fem',
		'sex',
		'sju',
		'åtta',
		'nio',
		'tio',
		'elva',
		'tolv',
		'tretton',
		'fjorton',
		'femton',
		'sexton',
		'sjutton',
		'arton',
		'nitton',
		'tjugo',
	),

	'months'=>array(
		'',
		'Januari',
		'Februari',
		'Mars',
		'April',
		'Maj',
		'Juni',
		'Juli',
		'Augusti',
		'September',
		'Oktober',
		'November',
		'December',
	),

	'weekdays'=>array(
		'måndag',
		'tisdag',
		'onsdag',
		'torsdag',
		'fredag',
		'lördag',
		'söndag',
	),

	'format_date'=>array(
		':e ',
		':a ',
		':a ',
		':e ',
		'Igår',
		'Idag',
		'{day}{mon}{yr}',
		'i {day}s kl. {hr}:{min}',
		'{day}{mon}{yr} kl {hr}:{min}',
	),

	'format_time'=>array(
		' minuter',
		' timmar',
		' dygn',
		' månader',
		' år ',
	),

	'accesses'=>array(

		array(
			'visitor',
			'member',
			'crew',
			'admin',
			'master',
		),

		array(
			'Besökare',
			'Medlem',
			'Crew',
			'Admin',
			'Master',
		),
	),

	'statuses'=>array(
		1=>'Online',
		2=>'Bekräftad',
		4=>'Accepterad',
		8=>'Varnad',
		16=>'Bannlyst',
		32=>'Borttagen',
		64=>'Dold',
		128=>'Gäst',
	),

	'name_format'=>'{gender}&nbsp;{name}',
	'name_female'=>'Sr.',
	'name_male'=>'Fr.',
);
